SMHI_NAMES = {
    "msl": "air_pressure_at_sea_level",
    "t": "air_temperature",
    "tcc_mean": "cloud_area_fraction",
    "hcc_mean": "cloud_area_fraction_high",
    "lcc_mean": "cloud_area_fraction_low",
    "mcc_mean": "cloud_area_fraction_medium",
    "pmax": "precipitation_amount_max",
    "pmin": "precipitation_amount_min",
    "tstm": "probability_of_thunder",
    "r": "relative_humidity",
    "wd": "wind_from_direction",
    "ws": "wind_speed",
    "gust": "wind_speed_of_gust",
    "vis": "horizontal_visibility",
    "spp": "percent_frozen_percipitation",
    "pcat": "percipitation_category",
    "pmean": "percipitation_mean",
    "pmedian": "percipitation_median",
    "Wsymb2": "wsymb2",
}